import { PathNode, Stage } from '@/types'

export const STAGES: Stage[] = [
  {
    id: 1,
    title: 'Arrival',
    subtitle: 'First 30 days',
    description: 'Establishing your legal and practical foundation in Germany.',
    color: '#1a1a2e',
    accentColor: '#4f8ef7',
  },
  {
    id: 2,
    title: 'Stabilization',
    subtitle: 'Months 1–6',
    description: 'Building your everyday life infrastructure.',
    color: '#0d1b2a',
    accentColor: '#38c9a0',
  },
  {
    id: 3,
    title: 'Integration',
    subtitle: 'Months 6–24',
    description: 'Deepening roots — language, community, systems.',
    color: '#0a1628',
    accentColor: '#f5a623',
  },
  {
    id: 4,
    title: 'Permanent Residency',
    subtitle: '21–60 months',
    description: 'Qualifying for long-term settlement rights.',
    color: '#0d0d1a',
    accentColor: '#b06ef3',
  },
  {
    id: 5,
    title: 'Citizenship',
    subtitle: '60–96 months',
    description: 'Becoming a German citizen.',
    color: '#0a0a14',
    accentColor: '#ff6b6b',
  },
]

export const PATH_NODES: PathNode[] = [
  // ─── STAGE 1: ARRIVAL ─────────────────────────────────────────────────────
  {
    id: 'anmeldung',
    title: 'Anmeldung',
    category: 'registration',
    stage: 1,
    description: 'Register your address at the local Einwohnermeldeamt (residents registration office). This is your first and most critical step.',
    whyItMatters: 'Almost everything in Germany is gated behind Anmeldung — your Tax ID, bank account, and many government services require it. Without it, you cannot legally work or access most services.',
    howTo: 'Book an appointment online at your city\'s Bürgeramt. Bring your passport, rental contract (Wohnungsgeberbestätigung from your landlord), and the Anmeldungsformular. Process takes ~15 minutes.',
    typicalDuration: '1–2 weeks to get appointment',
    dependencies: [],
    unlocks: ['tax_id', 'bank_account', 'social_security_number', 'rundfunkbeitrag'],
    officialLink: 'https://www.berlin.de/einwohnermeldeamt/',
  },
  {
    id: 'health_insurance',
    title: 'Health Insurance Activation',
    category: 'insurance',
    stage: 1,
    description: 'Activate your statutory (gesetzliche) or private health insurance. Germany mandates health coverage for all residents.',
    whyItMatters: 'Health insurance is legally required in Germany. Your employer cannot process payroll without it, and it\'s required for residence permit applications.',
    howTo: 'If employed, choose a statutory insurer (TK, AOK, Barmer) and register. Your employer pays ~50% of the premium. Self-employed or high earners may opt for private insurance.',
    typicalDuration: '1–5 days',
    dependencies: [],
    unlocks: ['residence_permit', 'doctor_registration'],
    officialLink: 'https://www.tk.de/en',
  },
  {
    id: 'tax_id',
    title: 'Tax ID (Steueridentifikationsnummer)',
    category: 'finance',
    stage: 1,
    description: 'Your permanent 11-digit tax identification number, automatically issued after Anmeldung.',
    whyItMatters: 'Required for salary payments. Without it, your employer taxes you at the maximum rate (class VI). Also needed for banking, investments, and tax returns.',
    howTo: 'No action required — it arrives by post 2–4 weeks after Anmeldung. If not received, contact Bundeszentralamt für Steuern.',
    typicalDuration: '2–4 weeks after Anmeldung',
    dependencies: ['anmeldung'],
    unlocks: ['tax_class_optimization'],
    officialLink: 'https://www.bzst.de',
  },
  {
    id: 'bank_account',
    title: 'German Bank Account',
    category: 'finance',
    stage: 1,
    description: 'Open a German current account (Girokonto) for salary, rent, and daily transactions.',
    whyItMatters: 'Required for salary deposits, rent payments via SEPA, and most German services. Many landlords refuse non-German accounts.',
    howTo: 'N26, DKB, or Commerzbank accept new immigrants. N26 is fully English, digital, and fastest (24–48h). Traditional banks may require Anmeldung confirmation.',
    typicalDuration: '1–5 days (digital banks)',
    dependencies: ['anmeldung'],
    unlocks: ['schufa_first_entry'],
  },
  {
    id: 'social_security_number',
    title: 'Social Security Number (Sozialversicherungsausweis)',
    category: 'legal',
    stage: 1,
    description: 'Your permanent German social security number, required for pension contributions and employment.',
    whyItMatters: 'Needed for your employer\'s payroll system. All pension contributions are tracked under this number — critical for PR eligibility later.',
    howTo: 'Your health insurer automatically registers you with Deutsche Rentenversicherung after you join. The card arrives by post within 2–4 weeks.',
    typicalDuration: '2–4 weeks',
    dependencies: ['anmeldung', 'health_insurance'],
    unlocks: ['pension_tracking'],
  },
  {
    id: 'rundfunkbeitrag',
    title: 'Rundfunkbeitrag Registration',
    category: 'registration',
    stage: 1,
    description: 'Register for the mandatory public broadcasting fee (€18.36/month per household).',
    whyItMatters: 'Legally required for all German households. Failure to register results in fines and debt collection. Can be shared if roommates already pay.',
    howTo: 'Register online at rundfunkbeitrag.de. If sharing an apartment where someone already pays, you can be exempted.',
    typicalDuration: '15 minutes',
    dependencies: ['anmeldung'],
    unlocks: [],
    officialLink: 'https://www.rundfunkbeitrag.de',
  },
  {
    id: 'sim_card',
    title: 'German SIM Card',
    category: 'registration',
    stage: 1,
    description: 'Get a German phone number and mobile plan for local communication and 2FA.',
    whyItMatters: 'German services, banks, and government portals often require a German phone number for SMS verification. Essential from day one.',
    howTo: 'Aldi Talk, Lidl Connect, or O2 prepaid available at supermarkets. Full contracts (Telekom, Vodafone) require Anmeldung.',
    typicalDuration: '1 day',
    dependencies: [],
    unlocks: [],
  },

  // ─── STAGE 2: STABILIZATION ────────────────────────────────────────────────
  {
    id: 'residence_permit',
    title: 'Residence Permit (Aufenthaltserlaubnis)',
    category: 'legal',
    stage: 2,
    description: 'Obtain or convert your visa to a residence permit at the Ausländerbehörde.',
    whyItMatters: 'Required to legally remain and work in Germany beyond your visa validity. Blue Card holders get an accelerated path to PR.',
    howTo: 'Book appointment at Ausländerbehörde. Required documents vary by visa type. Bring passport, Anmeldung, employment contract, salary slips, health insurance proof.',
    typicalDuration: '2–8 weeks for appointment',
    dependencies: ['anmeldung', 'health_insurance'],
    unlocks: ['blue_card', 'settlement_permit_eligibility'],
    officialLink: 'https://www.bamf.de',
  },
  {
    id: 'blue_card',
    title: 'EU Blue Card',
    category: 'legal',
    stage: 2,
    description: 'Apply for the EU Blue Card if you hold a university degree and meet the salary threshold.',
    whyItMatters: 'Blue Card holders can apply for permanent residency in 21 months (vs 5 years) with B1 German, or 33 months without. Massive timeline advantage.',
    howTo: 'Salary threshold 2025: €45,300 (general) or €41,041.80 (shortage occupations: IT, engineering, medical). Apply at Ausländerbehörde with employment contract.',
    typicalDuration: '4–8 weeks',
    dependencies: ['residence_permit'],
    unlocks: ['pr_fast_track'],
    applicableVisaTypes: ['blue_card', 'skilled_worker'],
  },
  {
    id: 'schufa_first_entry',
    title: 'SCHUFA First Entry',
    category: 'finance',
    stage: 2,
    description: 'Understand and start building your SCHUFA credit score — Germany\'s credit bureau.',
    whyItMatters: 'Landlords, phone contracts, and many services check SCHUFA. A positive score is built over time through regular bill payments and credit card usage.',
    howTo: 'Open a German bank account and maintain it well. Get a free SCHUFA report once per year at schufa.de. Avoid multiple credit applications in short periods.',
    typicalDuration: 'Ongoing',
    dependencies: ['bank_account'],
    unlocks: ['apartment_rental'],
    officialLink: 'https://www.schufa.de',
  },
  {
    id: 'driver_license_conversion',
    title: 'Driver\'s License Conversion',
    category: 'legal',
    stage: 2,
    description: 'Convert your foreign driver\'s license to a German one at the Fahrerlaubnisbehörde.',
    whyItMatters: 'EU licenses are valid indefinitely. Non-EU licenses (Turkey, US, etc.) must be converted — some within 6 months of residency. Driving on an expired foreign license results in fines.',
    howTo: 'Visit your local Straßenverkehrsamt. Some nationalities (Turkey, US) require a theory and/or practical test. Allow 4–12 weeks for processing.',
    typicalDuration: '4–12 weeks',
    dependencies: ['anmeldung'],
    unlocks: [],
    officialLink: 'https://www.kba.de',
  },
  {
    id: 'tax_class_optimization',
    title: 'Tax Class Optimization',
    category: 'finance',
    stage: 2,
    description: 'Understand your Steuerklasse (tax class) and optimize it for your life situation.',
    whyItMatters: 'Married couples can split to classes III/V, significantly increasing take-home pay. Wrong tax class costs hundreds of euros monthly.',
    howTo: 'Visit your local Finanzamt or apply online via ELSTER. Married couples should evaluate III/V vs IV/IV split. Changes take effect next month.',
    typicalDuration: '1–4 weeks to process',
    dependencies: ['tax_id'],
    unlocks: ['annual_tax_return'],
  },
  {
    id: 'doctor_registration',
    title: 'Register with a GP (Hausarzt)',
    category: 'insurance',
    stage: 2,
    description: 'Find and register with a general practitioner as your primary care doctor.',
    whyItMatters: 'In Germany, specialists usually require a referral from your GP. Without a Hausarzt, accessing healthcare is harder and more expensive.',
    howTo: 'Search jameda.de for doctors accepting new patients (Kassenpatient for statutory insurance). Bring your insurance card (Versichertenkarte) to registration.',
    typicalDuration: '1–4 weeks to get first appointment',
    dependencies: ['health_insurance'],
    unlocks: [],
  },

  // ─── STAGE 3: INTEGRATION ──────────────────────────────────────────────────
  {
    id: 'german_a1',
    title: 'German A1 Level',
    category: 'language',
    stage: 3,
    description: 'Reach A1 German — basic conversational ability and simple phrase comprehension.',
    whyItMatters: 'Required for family reunification visas. Also forms the foundation for B1 which unlocks faster PR.',
    howTo: 'VHS (Volkshochschule) offers subsidized courses across Germany. Apps: Duolingo, Babbel. Intensive courses reach A1 in 4–8 weeks.',
    typicalDuration: '4–8 weeks',
    dependencies: [],
    unlocks: ['german_a2'],
  },
  {
    id: 'german_a2',
    title: 'German A2 Level',
    category: 'language',
    stage: 3,
    description: 'Reach A2 German — ability to handle simple, direct exchanges and everyday situations.',
    whyItMatters: 'Required for some residence permit renewals. Building block toward B1.',
    howTo: 'Continue structured courses at VHS or Goethe-Institut. A2 exam can be taken at certified centers.',
    typicalDuration: '8–16 weeks after A1',
    dependencies: ['german_a1'],
    unlocks: ['german_b1'],
  },
  {
    id: 'german_b1',
    title: 'German B1 Level',
    category: 'language',
    stage: 3,
    description: 'Reach B1 German — independent user level, able to handle most situations.',
    whyItMatters: 'B1 is the key unlock for Blue Card holders applying for PR at 21 months. Also required for citizenship. The single most impactful language milestone.',
    howTo: 'Goethe-Institut B1 exam is widely accepted. Intensive courses: 6 months full-time. Consider Integrationskurs (government-subsidized, up to 900 hours).',
    typicalDuration: '6–18 months from scratch',
    dependencies: ['german_a2'],
    unlocks: ['pr_fast_track', 'citizenship_language'],
  },
  {
    id: 'pension_tracking',
    title: 'Pension Contribution Tracking',
    category: 'finance',
    stage: 3,
    description: 'Monitor your Deutsche Rentenversicherung contributions — these affect PR and citizenship eligibility.',
    whyItMatters: 'PR requires minimum 60 months of pension contributions (standard path). Blue Card path requires 12 months. Tracking ensures no gaps.',
    howTo: 'Create an account at eService.deutsche-rentenversicherung.de. Request your Renteninformation annually. Check for missing months.',
    typicalDuration: 'Ongoing',
    dependencies: ['social_security_number'],
    unlocks: ['pr_standard', 'pr_fast_track'],
    officialLink: 'https://www.deutsche-rentenversicherung.de',
  },
  {
    id: 'annual_tax_return',
    title: 'Annual Tax Return (Steuererklärung)',
    category: 'finance',
    stage: 3,
    description: 'File your annual German tax return for refunds and compliance.',
    whyItMatters: 'Most immigrants overpay taxes (wrong class, partial year). Average refund: €1,000–2,000. Filing is optional for employees but almost always financially beneficial.',
    howTo: 'Use ELSTER (free, official) or WISO Steuer / Taxfix apps. Deadline: July 31 of the following year. With a tax advisor (Steuerberater): December 31.',
    typicalDuration: '2–10 hours to complete',
    dependencies: ['tax_class_optimization'],
    unlocks: [],
    officialLink: 'https://www.elster.de',
  },
  {
    id: 'integrationskurs',
    title: 'Integration Course (Integrationskurs)',
    category: 'integration',
    stage: 3,
    description: 'Government-sponsored language + orientation course: 600h German + 100h German society.',
    whyItMatters: 'Subsidized path to B1. Completing the course and passing the final test (DTZ) counts toward citizenship naturalization requirements.',
    howTo: 'Apply via BAMF portal. Cost: €1.95/lesson hour (subsidized from ~€10). Priority access for recent arrivals and Blue Card holders.',
    typicalDuration: '6–12 months',
    dependencies: ['residence_permit'],
    unlocks: ['german_b1'],
    officialLink: 'https://www.bamf.de/integrationskurse',
  },

  // ─── STAGE 4: PERMANENT RESIDENCY ──────────────────────────────────────────
  {
    id: 'pr_fast_track',
    title: 'Permanent Residency — Blue Card Path (21 months)',
    category: 'milestone',
    stage: 4,
    description: 'Apply for the Niederlassungserlaubnis (settlement permit) via the EU Blue Card fast track.',
    whyItMatters: 'Full settlement rights. No longer tied to employer for visa. Unlimited stay. Foundation for citizenship.',
    howTo: 'Apply at Ausländerbehörde after 21 months with Blue Card + B1 certificate + 12 months pension contributions. Without B1: 33 months.',
    typicalDuration: '4–8 weeks processing',
    dependencies: ['blue_card', 'german_b1', 'pension_tracking'],
    unlocks: ['citizenship_residency'],
    applicableVisaTypes: ['blue_card'],
  },
  {
    id: 'pr_standard',
    title: 'Permanent Residency — Standard Path (5 years)',
    category: 'milestone',
    stage: 4,
    description: 'Apply for the Niederlassungserlaubnis after 5 years of legal residence.',
    whyItMatters: 'Full settlement rights. Unlimited stay. Foundation for citizenship.',
    howTo: 'Apply at Ausländerbehörde after 60 months. Requirements: B1 German, 60 pension contribution months, sufficient income, no criminal record.',
    typicalDuration: '4–8 weeks processing',
    dependencies: ['residence_permit', 'german_b1', 'pension_tracking'],
    unlocks: ['citizenship_residency'],
  },
  {
    id: 'settlement_permit_eligibility',
    title: 'Settlement Permit Readiness Check',
    category: 'milestone',
    stage: 4,
    description: 'Verify all requirements are met before submitting your PR application.',
    whyItMatters: 'Missing one requirement causes rejection and restarts the clock. A readiness check prevents costly mistakes.',
    howTo: 'Checklist: sufficient income (needs-based threshold), clean criminal record (Führungszeugnis), secure housing, health insurance, language certificate.',
    typicalDuration: '2–4 weeks document gathering',
    dependencies: ['residence_permit'],
    unlocks: ['pr_standard', 'pr_fast_track'],
  },

  // ─── STAGE 5: CITIZENSHIP ──────────────────────────────────────────────────
  {
    id: 'citizenship_residency',
    title: 'Citizenship Residency Requirement',
    category: 'milestone',
    stage: 5,
    description: 'Complete the required years of legal residence for naturalization.',
    whyItMatters: 'Standard: 8 years. Special integration achievement: 6 years. Exceptional achievement (volunteering, etc.): 5 years. PR holders: path is continuous.',
    howTo: 'Ensure no residence gaps. Trips abroad >6 months can interrupt continuity. Keep all residence permits and documents.',
    typicalDuration: 'Ongoing tracking',
    dependencies: ['pr_fast_track', 'pr_standard'],
    unlocks: ['citizenship_application'],
  },
  {
    id: 'citizenship_language',
    title: 'Citizenship Language Requirement (B1+)',
    category: 'language',
    stage: 5,
    description: 'Confirm B1 or higher German language level for naturalization application.',
    whyItMatters: 'Mandatory for citizenship. B2 or higher can improve your case. The certificate must be from a recognized institution.',
    howTo: 'Goethe-Institut, telc, or ÖSD certificates accepted. DTZ from Integrationskurs also valid.',
    typicalDuration: 'Already completed if B1 reached',
    dependencies: ['german_b1'],
    unlocks: ['citizenship_application'],
  },
  {
    id: 'einbuergerungstest',
    title: 'Einbürgerungstest (Naturalization Test)',
    category: 'integration',
    stage: 5,
    description: 'Pass the 33-question German citizenship test on law, society, and history.',
    whyItMatters: 'Required for naturalization. 17/33 correct to pass. Test covers German Basic Law, democratic principles, history.',
    howTo: 'Study at oeko.de/einbuergerungstest (official practice). Book test at BAMF. Test available in German.',
    typicalDuration: '4–8 weeks of preparation',
    dependencies: ['pr_fast_track', 'pr_standard'],
    unlocks: ['citizenship_application'],
    officialLink: 'https://www.bamf.de/einbuergerungstest',
  },
  {
    id: 'citizenship_application',
    title: 'Citizenship Application (Einbürgerung)',
    category: 'milestone',
    stage: 5,
    description: 'Submit your naturalization application at the Einbürgerungsbehörde.',
    whyItMatters: 'The final milestone. German citizenship grants EU freedom of movement, German passport (one of the world\'s strongest), full political rights.',
    howTo: 'Submit at your local Einbürgerungsbehörde. Processing: 6–24 months. Required: language cert, naturalization test, residency proof, income proof, renunciation of previous citizenship (usually).',
    typicalDuration: '6–24 months processing',
    dependencies: ['citizenship_residency', 'citizenship_language', 'einbuergerungstest'],
    unlocks: [],
    officialLink: 'https://www.bmi.bund.de/einbuergerung',
  },
]

export function getNodeById(id: string): PathNode | undefined {
  return PATH_NODES.find((n) => n.id === id)
}

export function getNodesByStage(stage: number): PathNode[] {
  return PATH_NODES.filter((n) => n.stage === stage)
}

export function getStageById(id: number): Stage | undefined {
  return STAGES.find((s) => s.id === id)
}
